name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter_spinkit: ^4.1.1
  animated_text_kit: ^1.3.0
  easy_web_view: ^1.0.1
  provider: ^4.0.4
  encrypt: ^3.3.1
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0
  firebase_auth: ^0.15.0+1
  local_auth: ^0.6.1+3
  flutter_dialogflow: ^0.1.3
  cloud_firestore: ^0.12.10+2
  circular_profile_avatar: ^1.0.6
  firebase_storage: ^3.1.3
  fluttertoast: ^3.1.3
  image_picker: ^0.6.3+4
  rflutter_alert: ^1.0.3
  cached_network_image: ^2.1.0+1
  firebase_messaging: ^5.0.2
  overlay_support: ^1.0.3
  wc_form_validators: ^0.1.1
  password_compromised: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  - assets/
